### ISSUE TITLE
Consecutive run of show changes the view

### ISSUE THREAD

**Issue by Schmetzler** [piccolomo/plotext#4] opened 2020-07-20 12:48 UTC
I found a strange bug, that when you run `plx.show()` multiple times,
the view is changed and not plotted the same each time.

I tried following scenario:

```
plx.scatter([10,2,3,5,2,1,5,13,4,2,5,3,2,1,5,6,17,12,15,4,5,4,3,2,5,6,9,8,12,18,5,3,2],rows=10,cols=25,point_color="red",equations=True)
plx.show()
plx.show()
plx.show()
```

I get:
```

                      •  │
            •            │
              •          │
     •       •       •   │
•                        ├5
                    •    │
           •       •     │
  •  •• •  •  ••• •    • │
 •••   •••       •     ••│
    •     •              ├0
┬─────────┬─────────┬────┘
0         10        20
x = 1.33 × col - -0.00 ± 0.67
y = 1.89 × row + 1.00 ± 0.94

                     •   │
            •            │
             •           │
      •      •       •   │
•                        ├5
                   ••    │
           •      •      │
   • •• •  •  ••• •   •  │
 •••   •••      ••     ••│
    •     •              ├0
┬─────────┬─────────┬────┘
0         10        20
x = 1.39 × col - -0.67 ± 0.69
y = 2.10 × row + 0.06 ± 1.05

                         │
            •        •   │
             •           │
      •      •      •    │
 •                       ├5
                   ••    │
   • •  •  •   •  •   •  │
  •   •  •    •••     •  │
  • •  • ••      •     • │
                         ├0
┬─────────┬─────────┬────┘
0         10        20
x = 1.45 × col - -1.36 ± 0.72
y = 2.33 × row - -0.99 ± 1.17
```

If I continue it eventually looks like:
```
                         │
                         │
                         │
                         │
           •••           ├5
           •••           │
                         │
                         │
                         │
                         ├0
┬─────────┬─────────┬────┘
0         10        20
x =  13.66 × col -  -147.93 ±   6.83
y = 766.27 × row - -3438.73 ± 383.14
```

I also tried different configurations (no rows and cols, no equations, no color)
everytime it is the same... something is changed if you call show() again.

**Comment by piccolomo** [comment] 2020-08-24 10:17
Dear Schmetzler,

thanks for the bug report. That is a real bug which I have now fixed (but not published yet). 

The problem is that, due to the size of the data pixel, each time the limits of the plot are calculated, they are set slightly bigger then the data set. The bug is due to the fact that the limits were calculated from the already expanded version and so each time you plot the limits expand and the plot appears to shrink. 

I should upload a new version soon with the bug fixed. In the mean time I recommend using the ` clear_plot ` function before each plot to avoid this problem.

Thanks, Savino

**Comment by piccolomo** [comment] 2020-12-20 02:11
Dear Schmetzler,

I have just upgraded plotext to a new version which solved the bug you reported. 
Here is the code:
```
import numpy as np
plt.scatter([10,2,3,5,2,1,5,13,4,2,5,3,2,1,5,6,17,12,15,4,5,4,3,2,5,6,9,8,12,18,5,3,2],rows=10,cols=25)
plt.show()
plt.show()
plt.show()
```
And the expected output:
```
                      •  ├ 17.8
            •            │     
              •          ├ 13.6
     •       •       •   │     
•                        ├ 9.4 
                    •    │     
           •       •     │     
  •  •• •  •  ••• •    • ├ 5.2 
 •••   •••       •     ••│     
    •     •              ├ 1.0 
┬─────┬─────┬─────┬─────┬┘     
0     8     16    24    32     

                      •  ├ 17.8
            •            │     
              •          ├ 13.6
     •       •       •   │     
•                        ├ 9.4 
                    •    │     
           •       •     │     
  •  •• •  •  ••• •    • ├ 5.2 
 •••   •••       •     ••│     
    •     •              ├ 1.0 
┬─────┬─────┬─────┬─────┬┘     
0     8     16    24    32     

                      •  ├ 17.8
            •            │     
              •          ├ 13.6
     •       •       •   │     
•                        ├ 9.4 
                    •    │     
           •       •     │     
  •  •• •  •  ••• •    • ├ 5.2 
 •••   •••       •     ••│     
    •     •              ├ 1.0 
┬─────┬─────┬─────┬─────┬┘     
0     8     16    24    32     

```

You can upgrade your `plotext` version using `pip install plotext --upgrade` and access the package documentation at[ pypi:plotext ](https://pypi.org/project/plotext/)and [github:plotext](https://github.com/piccolomo/plotext). 
The package has been just upgraded so there may be further issues: feel free to report any other, cause it is helpful! :-)

I hope it was useful and all the best using the package !

Savino

**Closed** 2020-12-20 02:11 UTC
